include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unawaited_futures: true
    use_super_parameters: true

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

dart_code_metrics:
  rules:
    - avoid-collection-methods-with-unrelated-types
