name: accessibility_tools
description: Checkers and tools to ensure your app remains accessible to all.
version: 0.0.1-dev.0

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  collection: ^1.16.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
